using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using EFConvention;

namespace Core.Configuration
{
    public class ContextConfiguration : IEFConventionConfigurator
    {
        public void Configure(IAutoContextFactoryConfiguration configuration)
        {
            configuration.AutomaticMigrationsEnabled = true;
            configuration.AutomaticMigrationDataLossAllowed = true;
            configuration.AutoGeneratedMigrationsEnabled = false;
            configuration.AutoMigrateGeneratedMigrationsEnabled = false;
        }
    }
}
